### ISSUE TITLE
mautrix-slack configuration format outdated

### ISSUE THREAD

**Issue by vale981** [spantaleev/matrix-docker-ansible-deploy#3479]
According to
https://github.com/mautrix/slack/issues/56
the mautrix-slack configuration format has changed. Now the service fails with 
```
Legacy bridge config detected, but hacky network config migrator is not set
```

I believe that the config format changes have to be ported in the playbook. Unfortunately, the only way I see right now is to look at the example config produced by
```
docker run --rm -v (pwd):/data:z dock.mau.dev/mautrix/slack:latest
```
and trying to figure things out from there.

**To Reproduce**
Enable mautrix-slack:
```yaml
matrix_mautrix_slack_enabled: true
```

**Comment by Park0** [comment]
https://github.com/mautrix/slack/releases/tag/v0.1.0
"Note that when upgrading from an older version, the config file will have to be recreated. Migrating old configs is not supported."

**Comment by Park0** [comment]
I just tried to update. It does some more but i have users with {% endraw% %} in there name. So it does not work fully as expected. The services does run so that's a start

**Comment by spantaleev** [comment]
Thanks for this report! It should be fixed now.

**Comment by vale981** [comment]
Thanks for the fix! I can report success on my end :).


 I thought about looking into it myself, but I would never have gotten it done so fast!

**Comment by Park0** [comment]
I still have some existing chats with the {% endraw% %} in the name. How can i force a update?
